{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"_DataCoOriginal\",\"d_Cliente\",\"d_Produto\",\"d_Loja\",\"f_Vendas\",\"_Medidas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "_DataCoOriginal",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Aponte diretamente para o arquivo de 95MB, não para a pasta!",
          "    Fonte = Csv.Document(File.Contents(\"C:\\gogogo\\gogogo\\data\\DataCoSupplyChainDataset.csv\"),[Delimiter=\",\", Columns=53, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    // Promove a primeira linha a cabeçalho",
          "    PromoverCabecalho = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    PromoverCabecalho"
        ],
        "kind": "m",
        "lineageTag": "2452f070-0ea2-4da0-8020-0ec8eb5c1c81"
      }
    ],
    "relationships": [
      {
        "name": "ca39667c-89f3-4aa4-b665-ffd138181287",
        "fromColumn": "Shipping Date",
        "fromTable": "f_Vendas",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ad92b6c9-8b10-41c3-bca4-8e318837daf3"
      },
      {
        "name": "AutoDetected_9154e42c-b5be-47e5-a8df-9b042185a1f4",
        "fromColumn": "Department Id",
        "fromTable": "f_Vendas",
        "toColumn": "Department Id",
        "toTable": "d_Loja"
      },
      {
        "name": "313a4fe3-da6e-a6bc-0ec3-f3838f5a6999",
        "fromColumn": "Order Customer Id",
        "fromTable": "f_Vendas",
        "toColumn": "Customer Id",
        "toTable": "d_Cliente"
      },
      {
        "name": "c83c33df-008b-76ad-70fe-e78eeeedb35e",
        "fromColumn": "Order Item Cardprod Id",
        "fromTable": "f_Vendas",
        "toColumn": "Product Card Id",
        "toTable": "d_Produto"
      },
      {
        "name": "f0374f8b-35bd-5c68-322f-22de7961a098",
        "fromColumn": "Order Date",
        "fromTable": "f_Vendas",
        "toColumn": "Date",
        "toTable": "d_Calendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "d_Cliente",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5714f85-255a-40dd-b005-dbe24e23af38",
            "sourceColumn": "Customer Id",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Fname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ca707e4-858f-4a2d-807a-cd27ce7daa40",
            "sourceColumn": "Customer Fname",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Lname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f9774dc-db47-4414-9473-6c3d3c8fbbf6",
            "sourceColumn": "Customer Lname",
            "summarizeBy": "none"
          },
          {
            "name": "Customer City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "005b5253-f63b-45b4-b1ef-918fe66de31f",
            "sourceColumn": "Customer City",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1a33a3e-e214-4a5a-9df4-418f3633d31f",
            "sourceColumn": "Customer Country",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dac367a9-6d73-4b59-82f5-0febdf2f0910",
            "sourceColumn": "Customer Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Customer State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8c0eab7-5001-4054-a332-4e0b05a9e68b",
            "sourceColumn": "Customer State",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64b8882f-324d-4586-b03d-8267deecb542",
            "sourceColumn": "Customer Zipcode",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "063c1869-3848-4bef-9e7a-73a0afdf744a",
        "partitions": [
          {
            "name": "d_Cliente",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Puxa os dados da consulta original",
                "    Fonte = _DataCoOriginal,",
                "    // 2. Seleciona apenas as colunas de cliente",
                "    ColunasSelecionadas = Table.SelectColumns(Fonte,{\"Customer Id\", \"Customer Fname\", \"Customer Lname\", \"Customer City\", \"Customer Country\", \"Customer Segment\", \"Customer State\", \"Customer Zipcode\"}),",
                "    // 3. Remove os clientes duplicados (deixa só 1 linha por cliente)",
                "    RemoveDuplicadas = Table.Distinct(ColunasSelecionadas, {\"Customer Id\"}),",
                "    // 4. Define o ID como Inteiro para otimizar a performance",
                "    TipoAlterado = Table.TransformColumnTypes(RemoveDuplicadas,{{\"Customer Id\", Int64.Type}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(TipoAlterado, {\"Customer Id\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "d_Produto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a90f0f29-1a2b-46de-ad61-dbcd0866140e",
            "sourceColumn": "Product Card Id",
            "summarizeBy": "none"
          },
          {
            "name": "Category Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ae2bd7a-4c80-40a5-ac3d-0a875b8bf999",
            "sourceColumn": "Category Id",
            "summarizeBy": "none"
          },
          {
            "name": "Category Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb0b69a6-1c7d-4236-9875-f9cd6d4d5477",
            "sourceColumn": "Category Name",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0aa5a93-196f-4706-91af-627179965b9f",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Product Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "8b4bdc99-9aed-4309-90fb-6b1aa7626868",
            "sourceColumn": "Product Price",
            "summarizeBy": "none"
          },
          {
            "name": "Product Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00958d07-0891-4b76-af41-75bcfaf7b7c5",
            "sourceColumn": "Product Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "13fd13c3-b8a3-49d1-938b-0387ecd25773",
        "partitions": [
          {
            "name": "d_Produto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = _DataCoOriginal,",
                "    ColunasSelecionadas = Table.SelectColumns(Fonte,{\"Product Card Id\", \"Category Id\", \"Category Name\", \"Product Name\", \"Product Price\", \"Product Status\"}),",
                "    RemoveDuplicadas = Table.Distinct(ColunasSelecionadas, {\"Product Card Id\"}),",
                "    // Ajusta IDs para Inteiro e Preço para Decimal Fixo (Moeda)",
                "    TipoAlterado = Table.TransformColumnTypes(RemoveDuplicadas,{{\"Product Card Id\", Int64.Type}, {\"Category Id\", Int64.Type}, {\"Product Price\", Currency.Type}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(TipoAlterado, {\"Product Card Id\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "d_Loja",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Department Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "631e593d-4c0e-4046-bca4-cbd8ff516bd1",
            "sourceColumn": "Department Id",
            "summarizeBy": "none"
          },
          {
            "name": "Department Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d667804-3052-40c2-8d29-7feefa1c09f2",
            "sourceColumn": "Department Name",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4ee2c7a-7e09-4c76-8341-2729b81ccd1d",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b2b9ea1-4d38-4c77-aac9-96dbebfbc986",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a670bf2-baaf-44c8-932e-eef932fdb004",
        "partitions": [
          {
            "name": "d_Loja",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = _DataCoOriginal,",
                "    ColunasSelecionadas = Table.SelectColumns(Fonte,{\"Department Id\", \"Department Name\", \"Latitude\", \"Longitude\"}),",
                "    RemoveDuplicadas = Table.Distinct(ColunasSelecionadas, {\"Department Id\"}),",
                "    TipoAlterado = Table.TransformColumnTypes(RemoveDuplicadas,{{\"Department Id\", Int64.Type}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(TipoAlterado, {\"Department Id\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "f_Vendas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18a2195d-7338-4abf-81e3-984adfd5ccbd",
            "sourceColumn": "Order Id",
            "summarizeBy": "count"
          },
          {
            "name": "Order Item Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a61e0892-cc64-449f-9b4c-a345248c99aa",
            "sourceColumn": "Order Item Id",
            "summarizeBy": "count"
          },
          {
            "name": "Order Customer Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02461f4e-39c3-4d82-af3e-09289a2b94f6",
            "sourceColumn": "Order Customer Id",
            "summarizeBy": "none"
          },
          {
            "name": "Order Item Cardprod Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c190b79b-a8c3-4ed6-9221-fdc31d255f9c",
            "sourceColumn": "Order Item Cardprod Id",
            "summarizeBy": "none"
          },
          {
            "name": "Department Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac88cdd7-64be-4abd-a814-2767f9b979cc",
            "sourceColumn": "Department Id",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e38be103-398a-45fd-9ef2-93ad064184f7",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "52f56517-0522-401b-adeb-7475e0c28fea",
            "sourceColumn": "Shipping Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ad92b6c9-8b10-41c3-bca4-8e318837daf3"
                },
                "isDefault": true,
                "relationship": "ca39667c-89f3-4aa4-b665-ffd138181287"
              }
            ]
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "d2846b6c-4ba1-42b5-a2b0-03c20399ea68",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Item Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "79a80005-fc1b-44b6-bb93-8cf1e5340097",
            "sourceColumn": "Order Item Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Profit Per Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "86080143-acb0-4026-b6d3-6f81f405e8ad",
            "sourceColumn": "Order Profit Per Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Benefit per order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "7e9835ac-1fe9-4ce7-b8b5-c8ca333e7fd4",
            "sourceColumn": "Benefit per order",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Item Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "a885842f-cb51-4c1c-8ec1-145be7666268",
            "sourceColumn": "Order Item Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Item Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "93935b0b-eab9-4196-b025-1bcccc679122",
            "sourceColumn": "Order Item Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Days for shipping (real)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff08561f-96ff-4395-953f-74ceb1a2f83b",
            "sourceColumn": "Days for shipping (real)",
            "summarizeBy": "none"
          },
          {
            "name": "Days for shipment (scheduled)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7bf16da-778a-4ce2-bba0-075e73a4b690",
            "sourceColumn": "Days for shipment (scheduled)",
            "summarizeBy": "none"
          },
          {
            "name": "Late_delivery_risk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5532f143-f5a9-4070-804b-f38aa211f759",
            "sourceColumn": "Late_delivery_risk",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "985883a2-64e6-4bb5-a4e6-e665c7b38eed",
            "sourceColumn": "Order Status",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91e84444-49f8-4c64-941e-dc4417d0c921",
            "sourceColumn": "Delivery Status",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46b39306-7e43-49cf-ac75-35ad7f2ca66b",
            "sourceColumn": "Shipping Mode",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "28ed4c14-2468-418f-8b5b-a1e222dbe0ab",
        "partitions": [
          {
            "name": "f_Vendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = _DataCoOriginal,",
                "    ColunasSelecionadas = Table.SelectColumns(Fonte,{\"Order Id\", \"Order Item Id\", \"Order Customer Id\", \"Order Item Cardprod Id\", \"Department Id\", \"order date (DateOrders)\", \"shipping date (DateOrders)\", \"Sales\", \"Order Item Total\", \"Order Profit Per Order\", \"Benefit per order\", \"Order Item Discount\", \"Order Item Quantity\", \"Days for shipping (real)\", \"Days for shipment (scheduled)\", \"Late_delivery_risk\", \"Order Status\", \"Delivery Status\", \"Shipping Mode\"}),",
                "    ",
                "    SepararDataPedido = Table.SplitColumn(ColunasSelecionadas, \"order date (DateOrders)\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Order Date\", \"Order Time\"}),",
                "    SepararDataEnvio = Table.SplitColumn(SepararDataPedido, \"shipping date (DateOrders)\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Shipping Date\", \"Shipping Time\"}),",
                "    RemoveHoras = Table.RemoveColumns(SepararDataEnvio,{\"Order Time\", \"Shipping Time\"}),",
                "",
                "    // CORREÇÃO CRÍTICA: Forçando o Power BI a ler Números e Datas no formato Americano (Ponto como decimal)",
                "    TransformacaoRegional = Table.TransformColumnTypes(RemoveHoras, {",
                "        {\"Order Date\", type date}, ",
                "        {\"Shipping Date\", type date},",
                "        {\"Sales\", Currency.Type},",
                "        {\"Order Item Total\", Currency.Type},",
                "        {\"Order Profit Per Order\", Currency.Type},",
                "        {\"Benefit per order\", Currency.Type},",
                "        {\"Order Item Discount\", Currency.Type}",
                "    }, \"en-US\"),",
                "",
                "    // Garantindo tipos inteiros para os IDs",
                "    TiposFinais = Table.TransformColumnTypes(TransformacaoRegional,{",
                "        {\"Order Id\", Int64.Type}, {\"Order Item Id\", Int64.Type}, {\"Order Customer Id\", Int64.Type}, {\"Order Item Cardprod Id\", Int64.Type}, {\"Department Id\", Int64.Type}, {\"Order Item Quantity\", Int64.Type}, {\"Late_delivery_risk\", Int64.Type}",
                "    })",
                "in",
                "    TiposFinais"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_b16c1975-b17a-4b25-b27d-de0e424eb8c0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "caa123b2-f3b2-400b-b4c0-dc174a98e3dd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0fcb6d2a-9e3b-45a8-8f9c-1dc166e8179f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "292bc2d1-3abd-4dd3-97a8-8f05ef72949a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b3b27cbd-d56c-4652-bc3a-cdb76ee984d2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61e7d895-fe88-4932-b626-b7bccb334896",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "08e9a57f-91c6-4f4f-be35-378870c0d9e4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a79af3a9-c28b-42f6-ac50-61babc551273",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b91708d1-877f-4449-95b3-9da9940cebe2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f1fd0a6d-3f69-4dde-bfdc-8eff5a6f486a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ed42b29e-c8d0-49fe-9ef6-26fbd535d615",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8a2e45ce-1a4f-48b6-a47a-02a04f87f31f",
                "ordinal": 3
              }
            ],
            "lineageTag": "a9a07c2d-f361-4179-9172-e56d9e20ad2c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "c2ffb21b-d36b-475c-a486-33a5881117b9",
        "partitions": [
          {
            "name": "DateTableTemplate_b16c1975-b17a-4b25-b27d-de0e424eb8c0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ad92b6c9-8b10-41c3-bca4-8e318837daf3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "27577f18-eed0-4660-8a97-881475f2f4b8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "747958d5-4b8d-47d2-ada4-9637e9d05894",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4da8d80e-612a-4e34-a621-c22811f88c63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1ce8025c-4639-4b4d-97b4-4664927a217f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dbc87745-a63e-4a21-95dc-fe37d37a518c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d9a40318-b7c9-4dc6-a35d-ad750e0858d2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0a1b6cd0-d609-44cf-a3e9-7d1895c74b8f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c604ee61-8c1f-4c4f-84e4-5787896c0515",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "16dbbce3-b52e-454c-8395-08ed6431c31e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8d16eec9-0d7c-4687-831b-8ef78b6fc50f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ffad210d-f342-4503-96ed-cebcc5211e1d",
                "ordinal": 3
              }
            ],
            "lineageTag": "e5ff776a-5e77-4b79-b896-caf4ce427f72"
          }
        ],
        "isHidden": true,
        "lineageTag": "398cbb6a-a978-4876-857c-ed358c1dad98",
        "partitions": [
          {
            "name": "LocalDateTable_ad92b6c9-8b10-41c3-bca4-8e318837daf3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('f_Vendas'[Shipping Date])), 1, 1), Date(Year(MAX('f_Vendas'[Shipping Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "d_Calendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1f3effd7512f4722a1b9f9ce0884814c"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "3301c9ac-dd54-4d8d-9c51-956e370c0974",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b4284781-dca1-40c3-b21e-049bcc4b8d43",
            "sourceColumn": "[Ano]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Abrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "63181d99-4311-4add-b9c6-58859edfa0bb",
            "sourceColumn": "[Mês Abrev]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "df5450d1-bfb4-4d7b-831d-3fbfe0dc4225",
            "sourceColumn": "[Mês Num]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "755ecefd-5764-4470-a5d8-ea4dad9d2ce1",
            "sourceColumn": "[Trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano-Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "345a6e24-5b14-41bf-908d-3d5b218e644b",
            "sourceColumn": "[Ano-Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "62e3e484-d26f-4c64-9d2c-4cdddba85e55",
        "partitions": [
          {
            "name": "d_Calendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    // Cria automaticamente as datas do primeiro dia da primeira venda logada até o último",
                "    CALENDARAUTO(),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mês Abrev\", FORMAT([Date], \"MMM\"),",
                "    \"Mês Num\", MONTH([Date]),",
                "    \"Trimestre\", \"T\" & FORMAT([Date], \"Q\"),",
                "    \"Ano-Mês\", FORMAT([Date], \"YYYY-MM\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35dfd9b0-f6f9-40e1-a0e3-fad28b51b4d3",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a3b326e0-6c00-4314-8689-05f7a2deb24d",
        "measures": [
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(f_Vendas[Sales])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "8b6bdbbe-84de-43ec-aae5-6bf9041197bd"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(f_Vendas[Order Profit Per Order])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "edd1a484-89c4-4ac7-9c41-d10bd9018ce1"
          },
          {
            "name": "Total Orders",
            "expression": "DISTINCTCOUNT(f_Vendas[Order Id])",
            "formatString": "0",
            "lineageTag": "9f9a8544-284c-44ab-a5d1-85baee066a2c"
          },
          {
            "name": "Ticket Medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "DIVIDE([Total Sales], [Total Orders], 0)",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "5f0f150c-f5a2-4eca-9dbd-f0e27d1a2c3b"
          },
          {
            "name": "Margem Lucro %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Profit], [Total Sales], 0)",
            "lineageTag": "18aedcdd-ac2c-473e-8ce6-04b434e1e81f"
          },
          {
            "name": "Desconto Medio %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR vTotalDiscount = SUM(f_Vendas[Order Item Discount])",
              "RETURN DIVIDE(vTotalDiscount, [Total Sales], 0)",
              ""
            ],
            "lineageTag": "d36f9e09-a832-4b13-b5c9-9b7edc5366b7"
          },
          {
            "name": "Rank Produtos",
            "expression": "RANKX(ALL(d_Produto[Product Name]), [Total Sales], , DESC, Dense)",
            "formatString": "0",
            "lineageTag": "69e083a1-4bb1-4579-b443-849fd437fd90"
          },
          {
            "name": "Sales YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "CALCULATE([Total Sales], DATESYTD(d_Calendario[Date]))",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "d43d38ae-809d-4dd1-a4fd-65c1594bdbdc"
          },
          {
            "name": "Sales Last Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "CALCULATE([Total Sales], SAMEPERIODLASTYEAR(d_Calendario[Date]))",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "d981e76b-736e-44f3-bbdb-2004022d0eb6"
          },
          {
            "name": "Crescimento YoY %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR vSalesLY = [Sales Last Year]",
              "RETURN DIVIDE([Total Sales] - vSalesLY, vSalesLY, 0)"
            ],
            "lineageTag": "7e6c25c2-2df8-4000-a6c5-de64acf2c649"
          },
          {
            "name": "Pedidos Atrasados",
            "expression": "CALCULATE([Total Orders], f_Vendas[Late_delivery_risk] = 1)",
            "formatString": "0",
            "lineageTag": "e5e45e44-dc03-4e37-ba0a-656e2fb73cf9"
          },
          {
            "name": "Taxa de Atrasos %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Pedidos Atrasados], [Total Orders], 0)",
            "lineageTag": "0aabed38-9861-47e8-98c3-41339aa6c0bc"
          },
          {
            "name": "Tempo Medio Entrega (Dias)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(f_Vendas[Days for shipping (real)])",
            "lineageTag": "81dba403-619d-4e53-974d-dc433f8cd1d7"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}